### ISSUE TITLE
[BUG] PSP - UI Scrolling bug

### ISSUE THREAD

**Issue by z2442** [z2442/daedalus#10]
Describe the bug:
When using the psp version of Daedalus with a large rom list the rom selector can go off screen.

To Reproduce
1)large rom list of around 100+
2)Scroll down using the analog stick 

Expected behavior:
The Rom Selector should stay within view of the UI.

Screenshots

Device:
 - Device: [psp Phat ] - Happens on all hardware 
 - FW:[6.61]
 - Daedalus Version [e.g. 1.1.6]

**Comment by DaedalusX64** [comment]
Fixed for 1.1.7 by reverting to a previous UI
