### ISSUE TITLE
[BUG] Daedalus freezes when resuming suspend on Vita

### ISSUE THREAD

**Issue by junetried** [z2442/daedalus#11]
Describe the bug
When Daedalus is open and the Vita is suspended, upon resuming, Daedalus will be frozen. 

To Reproduce
- Launch Daedalus on a Vita through Adrenaline. This works in the menu as well as in game.
- Press the power button to suspend the Vita.
- Press the power button again to resume.
- Daedalus is frozen and 

Expected behavior
Daedalus continues where it left off before you suspended.

Device:
 - Device: PlayStation Vita PCH-1001
 - FW: 3.65 Enso, Adrenaline Version 6.8
 - Daedalus Version 1.1.6

Additional context
Attempting to save state using Adrenaline seems to hang as well.
I found this issue on Adrenaline 6.1, updating to the latest version did not fix this.

**Comment by z2442** [comment]
Daedalus does not support sleep / suspend or a real psp or on Adrenaline. As for the save states did you mean Adrenaline save states or Daedalus save states?

**Comment by junetried** [comment]
Hmm, I don't remember noticing this on my PSP. I meant save states via Adrenaline, didn't know Daedalus had save states, I will try these later.

**Comment by junetried** [comment]
Save states work, helps quite a bit, thanks.

**Comment by z2442** [comment]
Welcome!
