### ISSUE TITLE
Cant enter sleep mode while running Daedalus on psp 2000

### ISSUE THREAD

**Issue by volt72** [z2442/daedalus#13]
I have a psp 2000 with 6.61 pro-c infinity, when I run Daedalus it works fine but when I try to put the psp in sleep mode it wont do anything till I exit the game to xmb. I tested running other Homebrew and iso's to try and narrow down the problem but I can go into sleep mode fine doing that so I am not too sure what the problem is.

**Comment by TheMrIron2** [comment]
This is a known issue; using the media engine CPU on the PSP for running custom code disables its usual functionality ie. sleep mode. We've considered making a ME-free build for Vita, but for now this just remains a known issue and a necessary consequence as a result of async audio existing.
